use_frameworks!

target 'Client-iOS' do
    # custom pods
  pod 'SwiftyGithub', :path => '../dev-Pods/SwiftyGithub'
  pod 'SwiftyBootstrap', :path => '../dev-Pods/SwiftyBootstrap'
  
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  pod 'SnapKit',    '~> 4.0.0'
  pod 'Alamofire',  '~> 5.0.0.beta.1'
  pod 'Swinject'
  pod 'OctoKit.swift'
  pod 'Toast-Swift', '~> 4.0.0'
end
